name: chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_chat_ui: ^1.6.12
  adaptive_theme: ^3.6.0
  provider: ^6.1.2
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  rest_api_package: ^1.0.0+2
  dio: ^5.4.2+1
  dropdown_search: ^5.0.6
  flutter_flip_card: ^0.0.5
  flutter_markdown: ^0.6.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true