import 'package:chat/model/language.dart';

const Set<Language> languages = {
  Language(code: 'af', name: 'Afrikaans'),
  Language(code: 'am', name: 'Amharic'),
  Language(code: 'ar', name: 'Arabic'),
  Language(code: 'ast', name: 'Asturian'),
  Language(code: 'az', name: 'Azerbaijani'),
  Language(code: 'ba', name: 'Bashkir'),
  Language(code: 'be', name: 'Belarusian'),
  Language(code: 'bg', name: 'Bulgarian'),
  Language(code: 'bn', name: 'Bengali'),
  Language(code: 'br', name: 'Breton'),
  Language(code: 'bs', name: 'Bosnian'),
  Language(code: 'ca', name: 'Catalan, Valencian'),
  Language(code: 'ceb', name: 'Cebuano'),
  Language(code: 'cs', name: 'Czech'),
  Language(code: 'cy', name: 'Welsh'),
  Language(code: 'da', name: 'Danish'),
  Language(code: 'de', name: 'German'),
  Language(code: 'el', name: 'Greek'),
  Language(code: 'en', name: 'English'),
  Language(code: 'es', name: 'Spanish'),
  Language(code: 'et', name: 'Estonian'),
  Language(code: 'fa', name: 'Persian'),
  Language(code: 'ff', name: 'Fulah'),
  Language(code: 'fi', name: 'Finnish'),
  Language(code: 'fr', name: 'French'),
  Language(code: 'fy', name: 'Western Frisian'),
  Language(code: 'ga', name: 'Irish'),
  Language(code: 'gd', name: 'Gaelic, Scottish Gaelic'),
  Language(code: 'gl', name: 'Galician'),
  Language(code: 'gu', name: 'Gujarati'),
  Language(code: 'ha', name: 'Hausa'),
  Language(code: 'he', name: 'Hebrew'),
  Language(code: 'hi', name: 'Hindi'),
  Language(code: 'hr', name: 'Croatian'),
  Language(code: 'ht', name: 'Haitian, Haitian Creole'),
  Language(code: 'hu', name: 'Hungarian'),
  Language(code: 'hy', name: 'Armenian'),
  Language(code: 'id', name: 'Indonesian'),
  Language(code: 'ig', name: 'Igbo'),
  Language(code: 'ilo', name: 'Iloko'),
  Language(code: 'is', name: 'Icelandic'),
  Language(code: 'it', name: 'Italian'),
  Language(code: 'ja', name: 'Japanese'),
  Language(code: 'jv', name: 'Javanese'),
  Language(code: 'ka', name: 'Georgian'),
  Language(code: 'kk', name: 'Kazakh'),
  Language(code: 'km', name: 'Central Khmer'),
  Language(code: 'kn', name: 'Kannada'),
  Language(code: 'ko', name: 'Korean'),
  Language(code: 'lb', name: 'Luxembourgish, Letzeburgesch'),
  Language(code: 'lg', name: 'Ganda'),
  Language(code: 'ln', name: 'Lingala'),
  Language(code: 'lo', name: 'Lao'),
  Language(code: 'lt', name: 'Lithuanian'),
  Language(code: 'lv', name: 'Latvian'),
  Language(code: 'mg', name: 'Malagasy'),
  Language(code: 'mk', name: 'Macedonian'),
  Language(code: 'ml', name: 'Malayalam'),
  Language(code: 'mn', name: 'Mongolian'),
  Language(code: 'mr', name: 'Marathi'),
  Language(code: 'ms', name: 'Malay'),
  Language(code: 'my', name: 'Burmese'),
  Language(code: 'ne', name: 'Nepali'),
  Language(code: 'nl', name: 'Dutch, Flemish'),
  Language(code: 'no', name: 'Norwegian'),
  Language(code: 'ns', name: 'Northern Sotho'),
  Language(code: 'oc', name: 'Occitan (post 1500)'),
  Language(code: 'or', name: 'Oriya'),
  Language(code: 'pa', name: 'Panjabi, Punjabi'),
  Language(code: 'pl', name: 'Polish'),
  Language(code: 'ps', name: 'Pushto, Pashto'),
  Language(code: 'pt', name: 'Portuguese'),
  Language(code: 'ro', name: 'Romanian, Moldavian, Moldovan'),
  Language(code: 'ru', name: 'Russian'),
  Language(code: 'sd', name: 'Sindhi'),
  Language(code: 'si', name: 'Sinhala, Sinhalese'),
  Language(code: 'sk', name: 'Slovak'),
  Language(code: 'sl', name: 'Slovenian'),
  Language(code: 'so', name: 'Somali'),
  Language(code: 'sq', name: 'Albanian'),
  Language(code: 'sr', name: 'Serbian'),
  Language(code: 'ss', name: 'Swati'),
  Language(code: 'su', name: 'Sundanese'),
  Language(code: 'sv', name: 'Swedish'),
  Language(code: 'sw', name: 'Swahili'),
  Language(code: 'ta', name: 'Tamil'),
  Language(code: 'th', name: 'Thai'),
  Language(code: 'tl', name: 'Tagalog'),
  Language(code: 'tn', name: 'Tswana'),
  Language(code: 'tr', name: 'Turkish'),
  Language(code: 'uk', name: 'Ukrainian'),
  Language(code: 'ur', name: 'Urdu'),
  Language(code: 'uz', name: 'Uzbek'),
  Language(code: 'vi', name: 'Vietnamese'),
  Language(code: 'wo', name: 'Wolof'),
  Language(code: 'xh', name: 'Xhosa'),
  Language(code: 'yi', name: 'Yiddish'),
  Language(code: 'yo', name: 'Yoruba'),
  Language(code: 'zh', name: 'Chinese'),
  Language(code: 'zu', name: 'Zulu'),
};
